### PR TITLE
Merge branch Lazerson into develop

### PR DESCRIPTION
**Pull request by lazersos**
The Lazerson branch contains a number of bugfixes and improvements and is up to date with develop.  The major updates are as follows:

- BEAMS3D various upgrades for generating input for ASCOT4 and ASCOT5.
- Added compilation support and updates for Marconi, Draco, Cobra, HGW_Theory, JFRS1
- Fixes missing SFINCS variables in make_all.inc
- Fixes STELLOPT profile optimization bug #53 
- LIBSTELL should now properly compile in serial
- Dependency files now moved out of Release and Debug, only one file necessary now.
- Various routines removed in accordance with `license` branch.
- Fixed bug in STELLOPT helicity calculations.

Please verify that the code compiles on your machines:

- [x] Macports (GCC, @lazersos )
- [x] Draco (Intel, @lazersos, @jcschmitt )
- [x] Cobra (Intel, @lazersos, @jcschmitt )
- [x] Marconi (Intel, @lazersos )
- [ ] Cori (Intel, @landreman, @zhucaoxiang)
- [x] Sunfire (@zhucaoxiang, @jbreslau, @mdjcole )
- [ ] Wisconsin Machines (@jcschmitt, @benjaminfaber, @aaroncbader)

### CODE REVIEW

**Comment by lazersos** [comment]
@zhucaoxiang Running the test with GCC and debug I don't get this error the test goes through just fine.  I'm building and checking on Draco with debug and the Intel compiler now.

**Comment by lazersos** [comment]
@zhucaoxiang I just tested on Draco and found no problem, although I see our debug flags are slightly different.  I'm going to rerun with more flags and check.

**Comment by lazersos** [comment]
@zhucaoxiang I'm able the replicate the issue if I expand my debug flags a bit.  I can also replicate a similar error but running VMEC alone.  I should note this doesn't appear durring a production run.  I suspect this has something to do with VMEC's use of initialized variables which imply an implicit `SAVE`. For example
```
       INTEGER :: test = 1
```
is the same as
```
      INTEGER, SAVE :: test=1
```
Also it should be noted that because of this one should always initialize variables in the main parts of a subroutine, not in the deffinitions.

I'll point this out to Marc but this is clearly a subtle VMEC bug not an issue we should fix in STELLOPT.

**Comment by zhucaoxiang** [comment]
@lazersos That's interesting. I will check your Intel compiler options and see if it works at PPPL. Just in case you don't know, the repo is now fully public. ORNL agrees we use VMEC as part of STELLOPT.

**Comment by zhucaoxiang** [comment]
@lazersos I tested on PPPL clusters. 

- GCC: Both release/debug versions are working
- Intel: The release version seems working, but the debug version has the issues that are reported above.

I would agree to merge, but just keep a record that these issues are actually existing.

Just for confirmation, `NTCC` is no longer required for any part of the code. Right? @lazersos I just removed the dependence in the Makefiles for PPPL.

**Comment by lazersos** [comment]
@zhucaoxiang Good idea.  We should create an issue here to track this bug, and I'll mirror the issue on the ORNL/VMEC Github site as well.

Regarding NTCC.  Yes we should be able to build all codes without needing to link to NTCC anymore.  In fact, the beam deposition routines in BEAMS3D now only need to know where the database files are and no longer rely upon linking to the libraries.  Also we no longer need the preprocessor directive either.

**Pull request merged**
