### PR TITLE
FORTRAN wall creation

### PR DESCRIPTION
**Pull request by DionEngels**

### CODE REVIEW

**Comment by lazersos** [comment]
@DionEngels I'm getting these messages on draco when I run the FIELDLINES test...any idea?  They do not show up for BEAMS3D:
```
srun --nodes=8 --ntasks-per-node=32 --time=0:30:00 -p express /u/sul/bin/xfieldlines -vmec NCSX_s1_coll -coil coils.NCSX -vac -vessel NCSX_wall_trimesh.dat -hitonly -field_start fieldlines_NCSX_s1.h5 114
srun: job 21080859 queued and waiting for resources
srun: job 21080859 has been allocated resources
FIELDLINES Version  1.80
-----  HDF5 (Parallel) Parameters  -----
   HDF5_version:   1.10 release: 07
-----  MPI Parameters  -----
   MPI_version:   3.01
   Intel(R) MPI Library 2018 Update 4 for Linux* OS

   Nproc_total:       256
   Nproc_shared:       32
   FILE: input.NCSX_s1_coll
----- Generating Starting Points -----
   FILE: fieldlines_NCSX_s1.h5
   NEW_LINES: 262144
      LINE #: 114
   OLD_LINES: 128
      NSTEPS:  24001
----- Input Parameters -----
   R   = [ 1.00000, 2.40000];  NR:    128
   PHI = [ 0.00000, 2.09440];  NPHI:   30
   Z   = [-1.00000, 1.00000];  NZ:    128
   # of Fieldlines: 262144
   VACUUM FIELDS ONLY!
   DIFFUSION OPERATOR TURNED ON!
----- COILS Information -----
   FILE: coils.NCSX
   Coil Periodicity:   3
   Current Systems:   10
   Current Type:      SCALED
   Num Coils  =    6  EXTCUR =  652.272 [kA]
   Num Coils  =    6  EXTCUR =  652.272 [kA]
   Num Coils  =    6  EXTCUR =  652.272 [kA]
   Num Coils  =    8  EXTCUR =    0.000 [A]
   Num Coils  =    8  EXTCUR =    0.000 [A]
   Num Coils  =    8  EXTCUR =    0.000 [A]
   Num Coils  =   12  EXTCUR =  -54.805 [kA]
   Num Coils  =    4  EXTCUR =    0.000 [A]
   Num Coils  =    2  EXTCUR =   94.241 [kA]
   Num Coils  =   18  EXTCUR =   45.514 [kA]
     Vacuum Field Calculation [000]%[  0]%[  1]%[  2]%[  3]%[  4]%[  5]%[  5]%[  6]%[  7]%[  8]%[  9]%[ 10]%[ 10]%[ 11]%[ 12]%[ 13]%[ 14]%[ 15]%[ 15]%[ 16]%[ 17]%[ 18]%[ 19]%[ 20]%[ 20]%[ 21]%[ 22]%[ 23]%[ 24]%[ 25]%[ 25]%[ 26]%[ 27]%[ 28]%[ 29]%[ 30]%[ 30]%[ 31]%[ 32]%[ 33]%[ 34]%[ 35]%[ 35]%[ 36]%[ 37]%[ 38]%[ 39]%[ 40]%[ 40]%[ 41]%[ 42]%[ 43]%[ 44]%[ 45]%[ 45]%[ 46]%[ 47]%[ 48]%[ 49]%[ 50]%[ 50]%[ 51]%[ 52]%[ 53]%[ 54]%[ 55]%[ 55]%[ 56]%[ 57]%[ 58]%[ 59]%[ 60]%[ 60]%[ 61]%[ 62]%[ 63]%[ 64]%[ 65]%[ 65]%[ 66]%[ 67]%[ 68]%[ 69]%[ 70]%[ 70]%[ 71]%[ 72]%[ 73]%[ 74]%[ 75]%[ 75]%[ 76]%[ 77]%[ 78]%[ 79]%[ 80]%[ 80]%[ 81]%[ 82]%[ 83]%[ 84]%[ 85]%[ 85]%[ 86]%[ 87]%[ 88]%[ 89]%[ 90]%[ 90]%[ 91]%[ 92]%[ 93]%[ 94]%[ 95]%[ 95]%[ 96]%[ 97]%[ 98]%[ 99]%[100 -----  Creating wall mesh  -----
 -----  Creating accelerated wall  -----
 -----  Vessel Information  -----
   Wall Name : NCSX
   Date      :  09-04-11
   Faces     :   12000
 Creating blocks. Chosen size:  0.404434444610013     
 Filling blocks. Number of blocks:          270
 -----  Done creating accelerated wall  -----
 Accelerated wall written to mesh file. Location: 
 NCSX_wall_trimesh_acc.dat                                                      
                                                                                
                                                                                
                    
 -----  Vessel Information  -----
   Wall Name : NCSX
   Date      :  09-04-11
   Faces     :   12000
   Blocks    :     270
   Mean faces per block:     56.00
   Highest faces per block:     476
----- Constructing Splines -----
   R   = [ 1.00000, 2.40000];  NR:    128
   PHI = [ 0.00000, 2.09440];  NPHI:   30
   Z   = [-1.00000, 1.00000];  NZ:    128
   MU  =     0.10000E-04
   HERMITE FORM: 1
----- FOLLOWING FIELD LINES -----
      Method: LSODE
       Lines:  262144
       HITONLY: only recording strike points
         Tol:  1.0000E-09  Type: 21
     Fieldline Calculation [  0]%  
----- WRITING DATA TO FILE -----
   FILE: fieldlines_NCSX_s1_coll.h5
212.40user 0.80system 3:36.06elapsed 98%CPU (0avgtext+0avgdata 129972maxresident)k
0inputs+0outputs (0major+20232minor)pagefaults 0swaps
212.20user 0.62system 3:35.89elapsed 98%CPU (0avgtext+0avgdata 133248maxresident)k
```

**Comment by DionEngels** [comment]
> @DionEngels I'm getting these messages on draco when I run the FIELDLINES test...any idea? They do not show up for BEAMS3D:
> 
> ```
> srun --nodes=8 --ntasks-per-node=32 --time=0:30:00 -p express /u/sul/bin/xfieldlines -vmec NCSX_s1_coll -coil coils.NCSX -vac -vessel NCSX_wall_trimesh.dat -hitonly -field_start fieldlines_NCSX_s1.h5 114
> srun: job 21080859 queued and waiting for resources
> srun: job 21080859 has been allocated resources
> FIELDLINES Version  1.80
> -----  HDF5 (Parallel) Parameters  -----
>    HDF5_version:   1.10 release: 07
> -----  MPI Parameters  -----
>    MPI_version:   3.01
>    Intel(R) MPI Library 2018 Update 4 for Linux* OS
> 
>    Nproc_total:       256
>    Nproc_shared:       32
>    FILE: input.NCSX_s1_coll
> ----- Generating Starting Points -----
>    FILE: fieldlines_NCSX_s1.h5
>    NEW_LINES: 262144
>       LINE #: 114
>    OLD_LINES: 128
>       NSTEPS:  24001
> ----- Input Parameters -----
>    R   = [ 1.00000, 2.40000];  NR:    128
>    PHI = [ 0.00000, 2.09440];  NPHI:   30
>    Z   = [-1.00000, 1.00000];  NZ:    128
>    # of Fieldlines: 262144
>    VACUUM FIELDS ONLY!
>    DIFFUSION OPERATOR TURNED ON!
> ----- COILS Information -----
>    FILE: coils.NCSX
>    Coil Periodicity:   3
>    Current Systems:   10
>    Current Type:      SCALED
>    Num Coils  =    6  EXTCUR =  652.272 [kA]
>    Num Coils  =    6  EXTCUR =  652.272 [kA]
>    Num Coils  =    6  EXTCUR =  652.272 [kA]
>    Num Coils  =    8  EXTCUR =    0.000 [A]
>    Num Coils  =    8  EXTCUR =    0.000 [A]
>    Num Coils  =    8  EXTCUR =    0.000 [A]
>    Num Coils  =   12  EXTCUR =  -54.805 [kA]
>    Num Coils  =    4  EXTCUR =    0.000 [A]
>    Num Coils  =    2  EXTCUR =   94.241 [kA]
>    Num Coils  =   18  EXTCUR =   45.514 [kA]
>      Vacuum Field Calculation [000]%[  0]%[  1]%[  2]%[  3]%[  4]%[  5]%[  5]%[  6]%[  7]%[  8]%[  9]%[ 10]%[ 10]%[ 11]%[ 12]%[ 13]%[ 14]%[ 15]%[ 15]%[ 16]%[ 17]%[ 18]%[ 19]%[ 20]%[ 20]%[ 21]%[ 22]%[ 23]%[ 24]%[ 25]%[ 25]%[ 26]%[ 27]%[ 28]%[ 29]%[ 30]%[ 30]%[ 31]%[ 32]%[ 33]%[ 34]%[ 35]%[ 35]%[ 36]%[ 37]%[ 38]%[ 39]%[ 40]%[ 40]%[ 41]%[ 42]%[ 43]%[ 44]%[ 45]%[ 45]%[ 46]%[ 47]%[ 48]%[ 49]%[ 50]%[ 50]%[ 51]%[ 52]%[ 53]%[ 54]%[ 55]%[ 55]%[ 56]%[ 57]%[ 58]%[ 59]%[ 60]%[ 60]%[ 61]%[ 62]%[ 63]%[ 64]%[ 65]%[ 65]%[ 66]%[ 67]%[ 68]%[ 69]%[ 70]%[ 70]%[ 71]%[ 72]%[ 73]%[ 74]%[ 75]%[ 75]%[ 76]%[ 77]%[ 78]%[ 79]%[ 80]%[ 80]%[ 81]%[ 82]%[ 83]%[ 84]%[ 85]%[ 85]%[ 86]%[ 87]%[ 88]%[ 89]%[ 90]%[ 90]%[ 91]%[ 92]%[ 93]%[ 94]%[ 95]%[ 95]%[ 96]%[ 97]%[ 98]%[ 99]%[100 -----  Creating wall mesh  -----
>  -----  Creating accelerated wall  -----
>  -----  Vessel Information  -----
>    Wall Name : NCSX
>    Date      :  09-04-11
>    Faces     :   12000
>  Creating blocks. Chosen size:  0.404434444610013     
>  Filling blocks. Number of blocks:          270
>  -----  Done creating accelerated wall  -----
>  Accelerated wall written to mesh file. Location: 
>  NCSX_wall_trimesh_acc.dat                                                      
>                                                                                 
>                                                                                 
>                     
>  -----  Vessel Information  -----
>    Wall Name : NCSX
>    Date      :  09-04-11
>    Faces     :   12000
>    Blocks    :     270
>    Mean faces per block:     56.00
>    Highest faces per block:     476
> ----- Constructing Splines -----
>    R   = [ 1.00000, 2.40000];  NR:    128
>    PHI = [ 0.00000, 2.09440];  NPHI:   30
>    Z   = [-1.00000, 1.00000];  NZ:    128
>    MU  =     0.10000E-04
>    HERMITE FORM: 1
> ----- FOLLOWING FIELD LINES -----
>       Method: LSODE
>        Lines:  262144
>        HITONLY: only recording strike points
>          Tol:  1.0000E-09  Type: 21
>      Fieldline Calculation [  0]%  
> ----- WRITING DATA TO FILE -----
>    FILE: fieldlines_NCSX_s1_coll.h5
> 212.40user 0.80system 3:36.06elapsed 98%CPU (0avgtext+0avgdata 129972maxresident)k
> 0inputs+0outputs (0major+20232minor)pagefaults 0swaps
> 212.20user 0.62system 3:35.89elapsed 98%CPU (0avgtext+0avgdata 133248maxresident)k
> ```

I am not sure which exact messages you are referring to, but two things might be different from what you've seen.
In the middle, it shows the info about making the accelerated wall. It first shows the raw input wall, then tells you that it is being accelerated, and then shows the output (number of blocks and such). 
At the bottom, it is showing the `time` output. Both `test_fieldlines_coll` and `test_fieldlines_coll_acc` have `time` in them from my testing. I could remove them if you'd like. This is not visible in this pull request since that already snuck into `Lazerson` from the last pull requests we did.

**Comment by lazersos** [comment]
@DionEngels Yep it's the time.  I'd appreciate it if you removed those as they could confuse people in the future...even the author of the code clearly.  :)

**Comment by DionEngels** [comment]
> @DionEngels Yep it's the time. I'd appreciate it if you removed those as they could confuse people in the future...even the author of the code clearly. :)

Yes, done!

**Comment by lazersos** [comment]
Made minor changes to another routine to make sure BEAMS3D is working within STELLOPT.  Doesn't really touch anything you've (@DionEngels) done.  As soon it passes the checks I'll merge it.

**Pull request merged**
