### PR TITLE
LIBSTELL: Test of OpenMP on Moller-Trumbore

### PR DESCRIPTION
**Pull request by DionEngels**

### CODE REVIEW

**Comment by zhucaoxiang** [comment]
@DionEngels Just a reminder, if you want to merge contents between different branches. You don't have to do it over the GitHub website. You can do it directly via commands locally, like `git merge some-branch`. Creating PR will send notifications to all the subscribers and I have received 10+ emails on this...

**Comment by DionEngels** [comment]
> @DionEngels Just a reminder, if you want to merge contents between different branches. You don't have to do it over the GitHub website. You can do it directly via commands locally, like `git merge some-branch`. Creating PR will send notifications to all the subscribers and I have received 10+ emails on this...

I did not know that people would get emails from my activity. I assumed it have been set up that people only get notifications if they are part of a certain PR. However, since this is not the case, I'll refrain from making PRs for everything I do and only when I want Samuel (who is my supervisor) to really check things. This should prevent some spam in the coming weeks.

**Comment by zhucaoxiang** [comment]
@DionEngels If people click "watch", by default they will receive PR notifications because in general PR is important. The goal of PR is mainly to push changes into the "master" and "develop" branches, which are protected. For all the other branches, you can just directly merge locally and push them to the remote repo. For example, for your case in this PR, you can do the following.
```
git fetch # fetch everything to make sure your local branches are synced with the remote
git checkout DionEngels-Moller-Trumbore # checkout to the working branch
git merge DionEngels-Moller-Trumbore-OpenMP # merge new stuff
< resolve conflicts, make commits>
git push origin DionEngels-Moller-Trumbore  # push your new contents to remote if you want to share it with someone else.
```

**Comment by DionEngels** [comment]
> @DionEngels If people click "watch", by default they will receive PR notifications because in general PR is important. The goal of PR is mainly to push changes into the "master" and "develop" branches, which are protected. For all the other branches, you can just directly merge locally and push them to the remote repo. For example, for your case in this PR, you can do the following.
> 
> ```
> git fetch # fetch everything to make sure your local branches are synced with the remote
> git checkout DionEngels-Moller-Trumbore # checkout to the working branch
> git merge DionEngels-Moller-Trumbore-OpenMP # merge new stuff
> < resolve conflicts, make commits>
> git push origin DionEngels-Moller-Trumbore  # push your new contents to remote if you want to share it with someone else.
> ```

Yes, I know how to do it, but thanks anyway for the explanation. By the way, I just checked, but you don't get notifications for all PRs by default. If you just simply watch the repo (like I am doing), you only get emails on notifications or when already participating in something. You probably have custom notifications set.

Either way, I'll avoid making PRs for everything from now on. Where I previously worked, making PRs for every change was the standard, and not only for protected branches. Either method is fine though, so I'll adopt this one for this repo.

**Comment by zhucaoxiang** [comment]
@DionEngels Okay, thanks for testing the notification. Probably it is because I am the administrator or my subscription is "all activity". Anyway, I do appreciate you adopt the new standard. Let's just create PR for the protected branches. @jcschmitt Maybe I was also wrong when you did the PRs.

**Pull request closed without merging**
